/**
 * Lawyer Game
 * 
 * Players are given a "hot take" (controversial opinion) and must defend it
 * as if they're a lawyer making their case in court.
 * Example: "Pineapple belongs on pizza" or "Morning people are untrustworthy"
 */

export interface LawyerGameConfig {
  hotTakes?: string[];
  timeoutSeconds?: number;
}

const DEFAULT_HOT_TAKES = [
  'Pineapple belongs on pizza',
  'Cereal is a soup',
  'Hot dogs are sandwiches',
  'Die Hard is a Christmas movie',
  'Toilet paper should hang over, not under',
  'Ketchup belongs on hot dogs',
  'Milk goes in before the cereal',
  'The best part of the Oreo is the cookie, not the cream',
  'Ranch dressing is better than all other condiments',
  'Water is not wet',
  'A taco is a sandwich',
  'Coffee is just bean soup',
  'The dress was definitely blue and black',
  'Cilantro tastes like soap and that\'s okay',
  'Well-done steak is the best way to eat steak',
  'Candy corn is actually delicious',
  'Raisins belong in cookies',
  'Breakfast food is overrated',
  'Pizza should be eaten with a fork and knife',
  'Ice cream is better when it\'s melted',
  'Cold pizza is better than hot pizza',
  'The crust is the best part of the bread',
  'Burgers should be eaten upside down',
  'Peanut butter and jelly sandwiches need butter',
  'Sushi is overrated',
  'Bacon is overrated',
  'Avocados are disgusting',
  'Mint chocolate chip is the worst ice cream flavor',
  'Ketchup belongs in the fridge',
  'Orange juice is better with pulp',
  'Sparkling water tastes like TV static',
  'The middle brownie piece is overrated',
  'Boneless wings are just chicken nuggets',
  'New York pizza is overrated',
  'In-N-Out Burger is overrated',
  'Sweet potato fries are superior to regular fries',
  'Chocolate cake is the worst cake',
  'Oatmeal raisin cookies are better than chocolate chip',
  'Ketchup on eggs is a crime',
  'Mayonnaise is the worst condiment',
  'Morning people are untrustworthy',
  'Night owls are more productive',
  'The best time to wake up is after noon',
  'Naps are a waste of time',
  'Working from home should be mandatory',
  'Casual Friday should be every day',
  'Meetings could have been emails',
  'The office thermostat should always be set to 72°F',
  'Open office plans are terrible',
  'Standing desks are a fad',
  'Business casual is an oxymoron',
  'Job interviews should be abolished',
  'Cover letters are pointless',
  'LinkedIn is just Facebook for people in suits',
  'Remote work is killing innovation',
  'Cats are better than dogs',
  'Dogs are overrated as pets',
  'Goldfish are the perfect pet',
  'Birds should not be kept as pets',
  'Snakes make great pets',
  'Pugs are not cute',
  'Pit bulls get an unfair reputation',
  'Outdoor cats should be illegal',
  'Small dogs are more annoying than large dogs',
  'Pet clothing is animal abuse',
  'Smartphones have made society worse',
  'Social media should require a license',
  'Texting is better than calling',
  'Email is a superior form of communication',
  'Autocorrect does more harm than good',
  'Dark mode is overrated',
  'The iPhone is overrated',
  'Android is superior to iOS',
  'Tablets are just big phones',
  'Smart watches are pointless',
  'Wireless earbuds are a scam',
  'The best phone keyboard was T9',
  'Selfie sticks should be banned',
  'QR codes are the worst invention',
  'Subscription services are ruining everything',
  'Books are better than movies',
  'The movie is always better than the book',
  'Spoilers actually make things more enjoyable',
  'Sequels are always worse',
  'Reboots are lazy',
  'Comic book movies are ruining cinema',
  'Streaming services have too much content',
  'Reality TV is the highest form of art',
  'Laugh tracks make shows better',
  'Black and white movies are boring',
  'Subtitles ruin the viewing experience',
  'Concerts are overrated',
  'Vinyl sounds worse than digital',
  'Modern music is better than classic music',
  'The Beatles are overrated',
  'Country music is the best genre',
  'Jazz is just random notes',
  'Classical music is boring',
  'Musicals are cringey',
  'Karaoke should be illegal',
  'Sitting is worse than smoking',
  'Running is terrible for your body',
  'Yoga is just expensive stretching',
  'Gym memberships are a waste of money',
  'Cardio is overrated',
  'Rest days are for the weak',
  'Protein shakes taste good',
  'Supplements are all scams',
  'The snooze button is evil',
  'Making your bed is pointless',
  'Showering at night is better than in the morning',
  'Socks should always be worn with sandals',
  'Cargo shorts are fashionable',
  'Crocs are the ultimate footwear',
  'Fedoras should make a comeback',
  'Socks and sandals is a legitimate fashion choice',
  'White socks with black shoes is fine',
  'Fashion is just expensive peer pressure',
  'Designer brands are a scam',
  'Fast fashion is better than expensive fashion',
  'School should start later in the day',
  'Homework is useless',
  'The education system is broken',
  'College is overrated',
  'Liberal arts degrees are worthless',
  'STEM is overvalued',
  'Summer break is too long',
  'Year-round school is better',
  'Cursive writing should be abolished',
  'Standardized tests are valuable',
  'Everyone should be required to take a gap year',
  'Student loans should be forgiven',
  'Trade school is better than college',
  'Group projects are the worst',
  'Pop quizzes are good teaching tools',
  'Being single is better than being in a relationship',
  'Long distance relationships never work',
  'Valentine\'s Day should be abolished',
  'Weddings are a waste of money',
  'Marriage is an outdated institution',
  'Destination weddings are selfish',
  'Having kids is overrated',
  'Pets are better than children',
  'An only child is the ideal family',
  'Living with your parents after 25 is fine',
  'Friendships are more important than family',
  'NYC is overrated',
  'Los Angeles is better than San Francisco',
  'Texas should be its own country',
  'Florida is actually great',
  'The Midwest is underrated',
  'Small towns are better than cities',
  'Suburbia is soul-crushing',
  'Living in a van is the dream',
  'Camping is just being homeless for fun',
  'Road trips are overrated',
  'Flying is better than driving',
  'Trains are the superior mode of transportation',
  'Public transportation should be free',
  'Cars should be banned in cities',
  'Sports are just adult entertainment for children\'s games',
  'Athletes are overpaid',
  'Cheerleading is not a sport',
  'Golf is not a sport',
  'NASCAR is just turning left',
  'Baseball is boring',
  'Soccer is better than football',
  'The designated hitter rule ruins baseball',
  'College sports are better than professional',
  'Participation trophies are good',
  'Esports are real sports',
  'Chess should be in the Olympics',
  'The Super Bowl halftime show is better than the game',
  'Money can buy happiness',
  'Being rich would solve all your problems',
  'Tipping should be abolished',
  'Cash is better than credit cards',
  'Budgeting is overrated',
  'Saving money is pointless with inflation',
  'Crypto is the future',
  'Investing is just gambling',
  'The lottery is a tax on people who are bad at math',
  'Gift cards are thoughtless presents',
  'Generic brands are always worse',
  'Coupons are worth the effort',
  'Black Friday is worth it',
  'Online shopping is killing communities',
  'Winter is the best season',
  'Summer is overrated',
  'Fall is just preparing for winter',
  'Spring allergies ruin everything',
  'Snow is terrible',
  'Rain is better than sunshine',
  'Cloudy days are superior',
  'The sun is overrated',
  'AC is more important than heating',
  'Cold weather is better than hot weather',
  'Children should not be allowed on airplanes',
  'Babies should not be allowed in movie theaters',
  'Talking during movies should be encouraged',
  'Clapping after movies is weird',
  'Popcorn at movies is overpriced but worth it',
  'Movie theater seats should all be recliners',
  '3D movies are better',
  'Animated movies are just for kids',
  'Horror movies are not scary',
  'Rom-coms are the best genre',
  'Documentaries are boring',
  'All museums should be free',
  'Abstract art is a scam',
  'Modern art is better than classical art',
  'Photography is not real art',
  'Digital art is not real art',
  'AI-generated art is legitimate art',
  'Comic books are literature',
  'Poetry is pretentious',
  'E-books are better than physical books',
  'Audiobooks are not really reading',
  'Reading multiple books at once is chaos',
  'Folding pages is fine',
  'Writing in books is encouraged',
  'Brushing teeth before breakfast is correct',
  'Toilet seats should always be down',
  'Double dipping is acceptable',
  'It\'s okay to wear shoes indoors',
  'Leaving dishes in the sink overnight is fine',
  'Microwaving fish at work is acceptable',
  'Loud chewing is not that bad',
  'Talking on speakerphone in public is fine',
  'Playing music without headphones is okay',
  'Clipping nails in public is acceptable',
  'Reading over someone\'s shoulder is fine',
  'Not washing hands after using the bathroom is okay',
  'Reheating food twice is safe',
  'The five-second rule is scientifically valid',
  'Sharing toothbrushes is fine between couples',
  'Bitcoin will replace all currency',
  'Social security should be abolished',
  'Taxes are theft',
  'Universal basic income is inevitable',
  'The gold standard should return',
  'Credit scores are a scam',
  'Capitalism is perfect',
  'Socialism is perfect',
  'Democracy is overrated',
  'Voting should be mandatory',
  'The voting age should be lowered to 16',
  'Politicians should have term limits',
  'The electoral college should be abolished',
  'Jury duty should be paid like a real job',
  'All drugs should be legalized',
  'The death penalty should be reinstated everywhere',
  'Prison should focus only on punishment',
  'White lies are always acceptable',
  'Honesty is overrated',
  'Everyone should learn to code',
  'Math is not necessary after high school',
  'History class is a waste of time',
  'PE should not be mandatory',
  'Detention is an effective punishment',
  'School uniforms should be mandatory',
  'Homework on weekends should be banned',
  'Teachers should be paid like doctors',
  'Online degrees are just as valuable',
  'Everyone should learn a second language',
  'Grades are an accurate measure of intelligence',
  'Multiple choice tests are the best assessment',
  'Open book exams are better',
  'Wikipedia is a reliable source',
  'Self-driving cars will never be safe',
  'Flying cars are inevitable',
  'We should colonize Mars immediately',
  'Space exploration is a waste of money',
  'Aliens definitely exist',
  'Time travel is possible',
  'The moon landing was real and boring',
  'Pluto is a planet',
  'Astrology is more accurate than astronomy',
  'Dinosaurs still exist somewhere',
  'Sharks are misunderstood and friendly',
  'Spiders are more scared of you',
  'Snakes make better pets than dogs',
  'Zoos should be abolished',
  'All animals should be vegan',
  'Hunting is conservation',
  'Fishing is cruel',
  'Horse racing should be banned',
  'Rodeos are animal abuse',
  'Sea World should be shut down',
  'Declawing cats is fine',
  'Breeding designer dogs is ethical',
  'Exotic pets should be legal everywhere',
  'All pitbulls are dangerous',
  'Chihuahuas are more aggressive than pitbulls',
  'Electric cars are worse for the environment',
  'Nuclear energy is the safest energy',
  'Wind turbines are ugly',
  'Solar panels decrease property value',
  'Climate change is exaggerated',
  'Recycling is pointless',
  'Paper bags are worse than plastic',
  'Organic food is a scam',
  'GMOs are perfectly safe',
  'Veganism is unhealthy',
  'Eating meat is unethical',
  'Dairy is necessary for strong bones',
  'Gluten sensitivity is made up',
  'Carbs are the enemy',
  'Fat makes you fat',
  'Breakfast is not the most important meal',
  'Eating after 8pm causes weight gain',
  'Meal timing doesn\'t matter',
  'Cheat days ruin diets',
  'Fad diets work long term',
  'Calories in, calories out is all that matters',
  'Intermittent fasting is dangerous',
  'Drinking 8 glasses of water daily is a myth',
  'Coffee stunts your growth',
  'Sugar causes hyperactivity in children',
  'Cracking knuckles causes arthritis',
  'Reading in dim light ruins your eyes',
  'You need 8 hours of sleep every night',
  'Napping makes you more tired',
  'Sleeping on your stomach is fine',
  'Left-handed people are more creative',
  'Multitasking makes you more productive',
  'Working longer hours means more productivity',
  'Brainstorming sessions are effective',
  'Open offices increase collaboration',
  'Remote work decreases productivity',
  'Checking emails on vacation is okay',
  'Working on weekends shows dedication',
  'Dress codes are necessary',
  'Ties serve a functional purpose',
  'High heels are comfortable once broken in',
  'Fashion trends should be followed',
  'Name brands are worth the price',
  'Matching socks is necessary',
  'Pajamas are acceptable outdoor wear',
  'Leggings are not pants',
  'Men should not wear shorts to the office',
  'Graphic tees are unprofessional',
  'Wearing the same outfit twice in a week is fine',
  'You should dress for the job you want',
  'Comfort over style always',
  'Style over comfort always',
  'Minimum wage should be $50/hour',
  'Billionaires should not exist',
  'Rich people work harder',
  'Poor people are poor by choice',
  'Money does not buy happiness',
  'Being broke builds character',
  'Debt is a tool, not a problem',
  'Credit cards are bad',
  'Renting is better than buying',
  'Buying is always better than renting',
  'College is always worth the debt',
  'Trade schools are better investments',
  'Internships should all be paid',
  'Unpaid internships are valuable experience',
  'Side hustles are necessary',
  'You should retire as early as possible',
  'Working past retirement age is sad',
  'Social media is toxic',
  'Facebook is for old people',
  'Instagram is fake',
  'Twitter makes people angry',
  'TikTok is rotting brains',
  'LinkedIn is useful',
  'Snapchat is pointless',
  'YouTube is educational',
  'Influencers are not real jobs',
  'Content creators work harder than traditional jobs',
  'Unboxing videos are entertaining',
  'Mukbang videos are gross',
  'ASMR is weird',
  'Podcasts are just people talking',
  'Video games are sports',
  'Mobile games are real games',
  'PC gaming is superior to console',
  'Console gaming is more convenient',
  'Nintendo makes the best games',
  'PlayStation is better than Xbox',
  'Gaming is a waste of time',
  'Video games cause violence',
  'Video games improve hand-eye coordination',
  'Streamers get paid too much',
  'Loot boxes are gambling',
  'Free-to-play games are better value',
  'Single-player games are dying',
  'Multiplayer ruins friendships',
  'Turn-based combat is outdated',
  'Graphics matter more than gameplay',
  'Indie games are better than AAA games',
  'Early access games are scams',
  'DLC is just cut content',
  'Microtransactions are fine',
  'Pay-to-win is acceptable',
  'Video game movies are always bad',
  'Board games are better than video games',
  'Monopoly is a good game',
  'Risk takes too long',
  'Scrabble is boring',
  'Chess is solved',
  'Checkers is more fun than chess',
  'Card games are gambling',
  'Poker is all luck',
  'Solitaire is the best card game',
  'Puzzles are frustrating, not fun',
  'Sudoku is overrated',
  'Crosswords are for old people'
];

export class LawyerGame {
  private hotTakes: string[];
  private timeoutSeconds: number;
  private currentHotTake: string | null = null;

  constructor(config: LawyerGameConfig = {}) {
    this.hotTakes = config.hotTakes || DEFAULT_HOT_TAKES;
    this.timeoutSeconds = config.timeoutSeconds || 90;

    if (this.hotTakes.length === 0) {
      throw new Error('LawyerGame requires at least one hot take');
    }
  }

  /**
   * Get a random hot take to defend
   */
  getRandomHotTake(): string {
    this.currentHotTake = this.hotTakes[Math.floor(Math.random() * this.hotTakes.length)];
    return this.currentHotTake;
  }

  /**
   * Get the current hot take (without randomizing)
   */
  getCurrentHotTake(): string {
    if (!this.currentHotTake) {
      throw new Error('No hot take selected yet. Call getRandomHotTake() first.');
    }
    return this.currentHotTake;
  }

  /**
   * Validate a player score
   */
  validateScore(score: number): boolean {
    return Number.isInteger(score) && score >= 0 && score <= 100;
  }

  /**
   * Get game rules
   */
  getRules(): string {
    return `Lawyer Game Rules:
1. Player receives a controversial "hot take" to defend
2. Player has ${this.timeoutSeconds} seconds to argue their case like a lawyer
3. Scoring is out of 100 points
4. Judge awards points based on persuasiveness, logic, and entertainment value
5. Player must defend the position, even if they disagree with it`;
  }

  /**
   * Get the number of available hot takes
   */
  getHotTakeCount(): number {
    return this.hotTakes.length;
  }

  /**
   * Get timeout in seconds
   */
  getTimeout(): number {
    return this.timeoutSeconds;
  }
}
